### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by figocia** [zendesk/samson#1410]
We were trying to upgrade our samson from v774 to the latest version.  However we had some trouble figuring out what new features were added to the latest version.  The current way this is possible is to go through the `Github Releases` and read through each of those notes, which sometimes do not provide the whole detail.  So we were wondering whether it's possible to have a release note/changelog in this repo for reference.

**Comment by grosser** [comment]
I'll close this as "won't fix" ... since it would be overhead to coordinate that and I'm not interested in taking on the additional work of policing the release/merge flow around writing release docs ... not against it, if you can find someone to either write them retroactively every few weeks or watch PRs and ask requesters to add release docs if they are missing and the change is "a new feature" ...
