### ISSUE TITLE
AngularJS all the way?

### ISSUE THREAD

**Issue by zendesk-shender** [zendesk/samson#177]
Now that there are more requests for dynamic updates for pages (current deploy page, current deploy badge in header, user search, job execution, ...), and since some of the pages already use AngularJS to some extent, can we start switching over to it fully?

Advantages:
- Making the samson rails app into an API focused backend will facilitate 3rd party scripting (QA in zendesk currently use some curl requests against samson APIs in their scripts).
- A more consistent UI which currently consists of Rails views, AngularJS, and direct jQuery HTML changes.
- More structured mechanism for updating content via data binding.

We don't have to do it all at once, but rather page by page, and a good starting point is the Current-Deploys page which shares 90% of the functionality of the Recent-Deploys page but one is written using Angular and the other is pure Rails.

**Comment by grosser** [comment]
I think most pages do not need to be live / fancy and our feature velocity will be higher when doing simpl-stupid html instead of live angular/ember/xyz. Most the js I saw was just plain old js and the only really fancy thing we do is the progress display.

**Comment by zendesk-shender** [comment]
@grosser 
Aye, but more and more feature requests are requiring JS:
- Updating current-deploys badge on menu bar
- Allowing user to hide/show deploy-group selection on stage-edit page to override.
- Environment Dashboard auto-refresh
- Pipeline progression UI updates
- ....

I think we've done a lot with the current backend HTML rendering, but to make this app shiney and responsive, I think it'll require a clientside JS framework and Radar integration.

**Comment by pswadi-zendesk** [comment]
@zendesk-shender Radar should be available now.

**Comment by vanchi-zendesk** [comment]
We are waiting behind a carson deploy to get all internal references out of
radar_client_rb. Should be available very soon.. :)

**Comment by zendesk-shender** [comment]
Thanks @vanchi-zendesk

**Comment by grosser** [comment]
For shiny feature we should use it, but what I want to avoid is making it
harder to add simple features.
Maybe some middle ground could be making static/simple things work
transparently,
but not sure if we realyy have to convert every last page or can just make
the fancy pages dynamic and the static pages static.

**Comment by zendesk-shender** [comment]
In terms of code maintenance, it might start getting ugly if some of the
pages are stored as templates for clientside JS, while the rest is stored
as rails templates.

And the 2 main reasons I brought this up originally were:
- Of the clientside JS, it's diverging already into
jquery/non-jquery/angular section, so settling on a single JS framework
would help regardless.
- There was a requirement to have dynamically changing UI elements that are
currently defined in the rails layout template, so if we change this to
angular, then maybe it calls for a more global change?

**Comment by grosser** [comment]
Maybe the dynamic element in the layout can be implemented using jquery ?
Basically I'd prefer a static app with sprinkles of js over a full blown js
app.
But once it's no longer sprinkles but half the pages switching all the way
is certainly easier,
I just don't think we have reached this point yet and hopefully don't need
to reach it / don't need to make everything super shiny-realtimy.
For example refreshing a dashboard every 60s would be a far simpler
approach then building it with realtime support + makes debugging easier +
does not need another service + means we never have stale data because xyz
bug happened etc.

**Comment by fneves** [comment]
I agree with moving towards a standard JS framework. The long term goal should be to have a full blown single js app running. But I also think that moving everything in one go is just too much work. 
We will need to do some work regarding a real API if we decide to go that way (which I think we should).

Plain html pages without any JS behaviour should be trivial to migrate and we should not be worrying about those too much for now. 

For anything new/refactored that uses JS behaviour, we should try to isolate them into a component and make them an angular directive, so that in the future the migration of that page, continues to be trivial.

Also, moving these components to an angular directive will make them easier to test (much easier than just JQuery).

**Comment by zendesk-shender** [comment]
Closing this, as angularjs is starting to propogate through the pages organically anyway, so progress is being made.
