### ISSUE TITLE
Circle CI cancelled deployment

### ISSUE THREAD

**Issue by mirago** [zendesk/samson#1880]
Hi guys, first of all thank you for samson, we started using it a few days ago and it already makes our life easier. This is rather a question than an issue, so sorry if this is not the place for questions.

We use samson with circle ci, after the build is done there is a webhook to samson and it then deploys the docker image to kubernetes. We do not use kubernetes plugin however. Yesterday I found one deployment, and it says 'Circle ci cancelled' it. It took about 8 minutes, which is unusual, as usually it takes about 3 minutes to deploy. Do you happen to know any reasons why this cancel happened? Does it timeout after certain amount of time? Is there any way to debug this?

**Comment by grosser** [comment]
Webhooks don't have a `cancel` callback, so that means something other happened.
Looking at the code we never write down who actually cancelled the deploy ... so the message is misleading ... should be something like "Circle CIs deploy was cancelled" ... https://github.com/zendesk/samson/pull/1881

Actual reason could be:
 - someone cancelling from the UI ... would find a DELETE request to `#destroy` in samsons logs
 - some kind of automatic failure
 - someone canceling it from the commandline

**Comment by mirago** [comment]
I see. Thanks for this, will have a look if there are any logs. Happy to close this.

**Comment by grosser** [comment]
also storing canceller with https://github.com/zendesk/samson/pull/1882
