### ISSUE TITLE
Global Concurrent Deploys Limit

### ISSUE THREAD

**Issue by mpchadwick** [zendesk/samson#2393]
It would be useful to be able to define a global limit for the number of concurrent deploys that Samson will run at any given time. For example, if I define a global limit of 3 and a user attempts to initiate a new deployment while 3 are in progress, Samson would add that deployment to a queue and start it when the next one finishes. Is this something that would be considered for Samson or better handled via a plugin?

**Comment by grosser** [comment]
Sounds useful in general, make a PR so the number is configureable via ENV var and default is unlimited. Might be best to implement this as "max concurrent jobs" in job_queue.rb

Implementation will be a little tricky since atm active jobs enqueue the next jobs when they are done, so you'll need to implement something like "if job is done and there are no other jobs in it's queue then grab a job from another queue that is not currently executing and run that" ... also it should be fair, so no finishing of a single queue but some fifo queue ... gotta be fun :D
