### ISSUE TITLE
setup! has git operations out of order

### ISSUE THREAD

**Issue by babbottscott** [zendesk/samson#260]
See https://github.com/zendesk/samson/commit/e23b036811c0fb51a71596b250d53862fe7c464c#commitcomment-10021535 and failed deploy of new app "billing" at https://samson.zende.sk/projects/billing/deploys/65234

On adding a new project, #setup! tries to #update! (git fetch) before #clone!, which leads to failure.  We worked around by changing the git repo URL.  On changing the URL, #clone! is called on the new URL.

**Comment by princemaple** [comment]
cc @zendesk/samson

**Comment by fneves** [comment]
The logic here is different than you are thinking. 

When the project is created the provided git repository url is automatically cloned into a local cached repo that will mirror the Git Repository [Project#L9](https://github.com/zendesk/samson/blob/master/app/models/project.rb#L9) 

This ```setup!``` method is only called when trying to do a deploy. What it does is to first update this cached repo (mirrored) to get the latest changes, tags and branches. Then clone it into a temporary directory so that we can support multiple deploys of the same, and then the temp repo is updated into the tag you've provided on the deploy.

**Comment by babbottscott** [comment]
Then I don't know what led to the broken state for the billing project.  If I see it happen again, I'll gather more info.  Thanks.
