### ISSUE TITLE
Github pull requests not triggering

### ISSUE THREAD

**Issue by adinhodovic** [zendesk/samson#3046]
Deploys are not triggered when opening or synchronizing a PR. Tried opening a pr to master and updating it, guessing it would trigger with the 'any branch' setting. Docker tag v2505.

Log:
```
INFO: Request is not supposed to trigger a deploy
```
Webhook mapping:
```
Any branch → dev stage for: Any pull request
```

Partial Payload (can post full if needed):
```
{
  "payload": "{\"action\":\"opened\",\"number\":2,\"pull_request\":{\"url\"}}
}
```

Same thing for synchronize:

Webhook mapping:
```
Any branch → dev stage for: Any pull request
```
Payload:
```
"payload": "{\"action\":\"synchronize\",\"number\":9,\"pull_request\":{\"url\"}}
```
Log:
```
INFO: Request is not supposed to trigger a deploy
```

**Am I missing something?**

**Comment by grosser** [comment]
code looks like it should work `VALID_ACTIONS = ['opened', 'edited', 'synchronize'].freeze`
and then `return false if data['state'] != 'open' || !VALID_ACTIONS.include?(action)` ... I think the issue is `WEBHOOK_FILTER = /(^|\s)\[samson review\]($|\s)/i` ... try adding `[samson review]` to the PR and see what happens

**Comment by adinhodovic** [comment]
> code looks like it should work `VALID_ACTIONS = ['opened', 'edited', 'synchronize'].freeze`
> and then `return false if data['state'] != 'open' || !VALID_ACTIONS.include?(action)` ... I think the issue is `WEBHOOK_FILTER = /(^|\s)\[samson review\]($|\s)/i` ... try adding `[samson review]` to the PR and see what happens

Opening a pr with [samson review] works fine, is that the intended functionality? Isnt this only for edit actions: 
```To trigger a deploy from an edit - it should only be when the edit is related to adding the text [samson review]```

**Comment by grosser** [comment]
hmm it's like this since the beginning :(
https://github.com/zendesk/samson/pull/746

your expectation makes more sense to me though, trigger on opening a PR and enable re-review for "Any PR" ... so the change we'd need is to migrate all `any_pr` settings to be `any_pr_with_keyword` (or something like that) and then add that as an option with a new any_pr that behaves as you described

please make a PR if you can, it's always great to get fresh eyes on the code to see what's good/bad if you get stuck @zendesk/bre or I can help out :)

**Comment by grosser** [comment]
and a /cc for @mwerner just for fun :)
