### ISSUE TITLE
Allow multiple pod selection during New Kubernetes Deploy Group Role setup

### ISSUE THREAD

**Issue by g-marius** [zendesk/samson#3210]
It's the second time I need to create a k8s project for talk teams and was thinking of a feature request for the "New Kubernetes Deploy Group Role" section to either or both:
 - allow for mass deploy groups selection for pods when creating a new roles. In attached case I would like to set up kafka-consumer role in one go for all known production pods as all will share the same policies (cpu/mem wise)
 - map k8s production/staging of all active pods in a placeholder that when selecting will create the role in each pod.

This is the section I am referring to:
<img width="668" alt="screenshot 2019-03-06 at 08 47 57" src="https://user-images.githubusercontent.com/11991519/53868093-26aa3a00-3fed-11e9-8310-d539fa581064.png">

**Comment by grosser** [comment]
We have a "mass edit" form, that might be a better fit ... we could allow duplicating a row there and then mark it a new.

Another approach might be to allow selecting environments in the dropdown and then behind the scenes it would create deploy-group-roles for all currently used deploy groups (never all, since there is too much junk) ... this could get ugly though if for some reason validations fail and would make the edit flow non-standard, which I'd like to avoid anyway.

**Comment by grosser** [comment]
... could also offer a "Save and add another" that then copies all the values, that would be pretty straight forward and not need much of a logic change ...

**Comment by grosser** [comment]
check out https://github.com/zendesk/samson/pull/3212
