### ISSUE TITLE
Environment Variables for a particular deploy are not being set

### ISSUE THREAD

**Issue by bhavya0692** [zendesk/samson#3774]
Before deploying to a particular stage, when environment variables are added in the "Extra Environment Variables for this deploy" section, variables are not being set. Whereas, environment variables are being set when mentioned for a particular stage.

**Comment by bhavya0692** [comment]
I am currently using version 3144

**Comment by grosser** [comment]
it's not supposed to work at all :D
`# TODO: remove this, just for backwards compatibility and broken since it does not check scope`

env vars are written to `.env*` files and should be sourced from there / shipped to the app from there ... they are not automatically set into the environment of the executing command
