### ISSUE TITLE
Issue with deploy logs

### ISSUE THREAD

**Issue by nomadium** [zendesk/samson#466]
Hi folks,

Recently I deployed samson and I noticed "live logs" feature for deploys is not working well for me.

Samson is able to successfully complete deploys but  I can't see the console output until the deploy finishes. I usually wait 5 minutes or so to refresh the app and see the logs.

I tried to debug this but I see server logs for streams returning 200 and when I open developer console in my browser to see network traffic, I can see 200 responses but with an empty body, i.e. ```/streams/15``` returns 200 but with an empty body.

I was able to see console output for my deploys when I ran samson in development mode. Now, I have deployed samson in production and I can't see this output. I redeployed in development again to test but I still can't see the output.

Do you have any idea of how debug this issue?

Thanks.

**Comment by nomadium** [comment]
This was just nginx misconfiguration on my side, sorry for the noise.

I fixed my issue after adding this setting in the location defined for samson:

```proxy_http_version 1.1```

Thanks.

**Comment by ibrahima** [comment]
Wow, thanks for this thread, was having the same issue and was very confused! This might be something useful to add to the documentation. In general, it'd be nice to have some instructions for setting up Samson in production rather than just in development mode. Seems like the right thing to do is follow a standard Puma/nginx setup but little things like this can trip people up.

I'll try and send a PR when I have time!

**Comment by grosser** [comment]
yes please, first time setup is always hard to get right after the fact :D
