### ISSUE TITLE
Docker integration does not work with Amazon ECR

### ISSUE THREAD

**Issue by rata** [zendesk/samson#849]
Hi,

Amazon ECR does not uses a user/pass auth. You need to run something like: 

```
aws ecr get-login --region=us-west-2
```

in the aws-shell and it gives you a user/pass that is valid for ~12 hours. So, setting the DOCKER_REGISTRY_USER and DOCKER_REGISTRY_PASS env variables at startup isn't really an option.

Is there any plan or idea how to integrate support for Amazon ECR in docker builds?

**Comment by grosser** [comment]
afaik there are no plans to support it ... how about setting `DOCKER_REGISTRY_AUTH` to the command that will return user/password ?

**Comment by rata** [comment]
And use that env var how/when? Like set the user and pass env vars from the
output of that command that is run before running any docker build?

The command returns a docker command, something like:

```
docker login -u AWS -p <some-pass> -e none https://<your-id>.dkr.ecr.us-west-2.amazonaws.com
```

When running this, it stores the credentials in ~/.docker/config.json. What do
you think of using the config.json file?

**Comment by grosser** [comment]
could use that if user/pass is not set in the env ... would that fix your issue / how would you make sure it's filled prior to being needed ?

maybe do a hacky PR with a solution that would work and then we take the discussion thee ?

**Comment by jonmoter** [comment]
We don't have a solution yet, but if we wanted to support it, here's one possibility.

With the [docker gem](https://github.com/swipely/docker-api#global-calls) we're using, you can authenticate with the registry by calling:

```
Docker.authenticate!('username' => 'MY_ACCOUNT', 'password' => `MY_PASSWORD`)
```

and then it will use those credentials when connecting to the registry.

As far as I can tell from the docs, the tokens that you get back from Amazon last for 12 hours, so they need to be regularly updated.  So, if we wanted to support this, we could include the aws-sdk gem to call [get-login](http://docs.aws.amazon.com/sdkforruby/api/Aws/ECR/Client.html#get_authorization_token-instance_method), and have a thread that does something like:

```ruby
ecr_client = Aws::ECR::Client.new(region: 'us-west-2', credentials: somethingsomething)
loop do
  response = ecr_client.get_authorization_token
  auth_token = response.authorization_data[0].authorization_token
  Docker.authenticate!('username' => 'AWS', 'password' => auth_token)
  sleep(6.hours)
end
```

I haven't tested this, but in theory, something like this could work?

I'm looking into using ECR as well, but I could see that being difficult to use, since we'd need to keep refreshing the token.

**Comment by rata** [comment]
Thanks! Juan is working in a way to integrate ECR and will do the PR when he has something
