### ISSUE TITLE
Run db migrations before kubernetes deployment

### ISSUE THREAD

**Issue by rata** [zendesk/samson#869]
Hi!

We need a way to run commands, to at least run the db migrations, before the deployment. We want this to be run in only one place and have logs and no auto-retry if it fails, etc. and in kubernetes ML it was recommended to do it as a another stage, just before the actual deploy.

Can I ask what do you do today to deploy apps on kubernetes that need db migrations? How do you handle that?

It will be nice to have the possibility to run arbitrary commands (maybe inside the docker image, to run the migrations too) but with a way to run the db migrations, it's fine for us for now :)

**Comment by jonmoter** [comment]
That's on my "todo" list as something to figure out.

My thinking was to use a [Kubernetes Job](http://kubernetes.io/docs/user-guide/jobs/), using the same `Build` that you're going to deploy, but running a command like `rake db:migrate` instead.

I haven't yet thought of a good UI or workflow to make that happen. I'm open to ideas.

Another thing I haven't figured out is how an end user of Kubernetes would do the equivalent of a `rails console` for an app running in Kubernetes.

**Comment by rata** [comment]
@jonmoter: A job is an interesting think to be able to schedule in a stage, but I haven't use them. I'm not sure if it can be configured to not-restart if it fails (with a failed migration, you don't want it to restart probably). Do you know? I will try early next week if not :)

Maybe a YAML with jobs, just like the deployment job, and in the UI they can be associated in order with different "stages" ? (I know they are not stages now, but something like that will be needed I think)

**Comment by jonmoter** [comment]
Yup, you can set the [restartPolicy](http://kubernetes.io/docs/user-guide/jobs/#handling-pod-and-container-failures) of a job to `OnFailure` or `Never`.

**Comment by rata** [comment]
On Sun, Apr 24, 2016 at 10:30:05AM -0700, Jon Moter wrote:
> Yup, you can set the
> [restartPolicy](http://kubernetes.io/docs/user-guide/jobs/#handling-pod-and-container-failures)
> of a job to `OnFailure` or `Never`.

Seems like a nice way to do it! It should be useful besides this.

Perhaps when init containers are a reality (not sure if they will be implemented
in k8s or not, yet) schema can be done with init-containers, but this way seems
quite useful meanwhile =)

**Comment by jbarreneche** [comment]
@jonmoter Hi, I'd like to know if you've been working in the posibility of triggering kubernetes jobs for running macros (which would at least allow to have a workaround for running database migrations manually before deploying).

If not, I'd like to take a shot at implementing it. I have a rough idea on how to do it but any help/suggestion would be greatly appreciated :)

**Comment by jonmoter** [comment]
Haven't done any work on it yet, but open to contributions.

Seems like you could modify the Macro code for Kubernetes-enabled deployments so that you specify a Build (or git ref), a Deploy Group, and a config file containing a `Job`. Running the macro would schedule the `Job` in Kubernetes, watch for its result, and possibly stream its logs.

**Comment by grosser** [comment]
would be interesting if a role could be a job or something like that and
then we execute them via kubectl run before deploying the rest, so the
deploy stays atomic / behaves like in old capistrano days ... (we'd execute
all jobs before doing the deploy)

**Comment by jonmoter** [comment]
Yeah, `rake db:migrate` is interesting, 'cause you want to run it once in each DeployGroup for each new version of the project.  But you should only run it once, and you need to run it before you try deploying any of the other roles.

Something like that feels like part of a deploy "pipeline", since you want the next step to block on its completion.  But it's part of the deployment of a stage, not a completely separate stage.

So Samson doesn't have a really great way of modeling this, given how it's currently constructed. We're starting to bump up against some of the limitations of Samson, which weren't as obvious when Capistrano took care of a lot of that logic. (At least at Zendesk.)

For a project (and/or a Stage?) we could configure one or more pre-deploy Jobs, which point to a YAML file in the `kubernetes` subdirectory that contains an object of kind `Job`.  That could be executed before a stage, or as a macro, as @jbarreneche suggested.

**Comment by rata** [comment]
On Wed, Jun 01, 2016 at 05:35:20PM -0700, Jon Moter wrote:
> Yeah, `rake db:migrate` is interesting, 'cause you want to run it once in each DeployGroup for each new version of the project.  But you should only run it once, and you need to run it before you try deploying any of the other roles.
> 
> Something like that feels like part of a deploy "pipeline", since you want the next step to block on its completion.  But it's part of the deployment of a stage, not a completely separate stage.
> 
> So Samson doesn't have a really great way of modeling this, given how it's currently constructed. We're starting to bump up against some of the limitations of Samson, which weren't as obvious when Capistrano took care of a lot of that logic. (At least at Zendesk.)
> 
> For a project (and/or a Stage?) we could configure one or more pre-deploy Jobs, which point to a YAML file in the `kubernetes` subdirectory that contains an object of kind `Job`.  That could be executed before a stage, or as a macro, as @jbarreneche suggested.

Yeah, that seems fine.

Also, being able to run a job is nice to do other things, like data migrations
after a deploy, etc. :)

**Comment by jbarreneche** [comment]
@jonmoter Hi, we are testing the implementation you currently have for running jobs before deployment. As far as we have tested, it seems that jobs are fired before deployment (which is good) and waited for them to be alive, but currently samson doesn't wait for those jobs to finish. 
In the case of database migrations this can be a problem (because the app may boot and see a given version for the schema that will later change). 
Are you aware of this? Is this the intended behaviour?

**Comment by grosser** [comment]
Not aware and not intended ... I guess ours are just running fast enough that we did not notice ... fix coming up :)

**Comment by jbarreneche** [comment]
@grosser great, good to know :) Let me know if I can help with anything. 
We are back on moving forward with our kubernetes migration, so we were updating our samson and bumped with this problem. With that implementation (ie. waiting for the job to be completed), this issue can be closed (at least for our use cases).
Thanks again!
